import type { PublicContent } from "@/types/content";

export const STATIC_CONTENT: PublicContent = {
  settings: {
    brandName: "WEBRING",
    logoUrl: "",
    colors: {
      background: "#050505",
      surface: "#111111",
      text: "#F7F3EA",
      muted: "#A8A29A",
      accent: "#D7FF45",
    },
    seo: {
      title: "WEBRING — AI-Powered Product Photography & Brand Visual Studio",
      description:
        "We engineer visual reality. AI-powered product photography, lifestyle imagery, and brand identity for e-commerce brands worldwide.",
    },
    hero: {
      eyebrow: "AI × Photography × Branding",
      headline: "We Engineer Visual Reality.",
      subheadline:
        "From raw product shots to studio-perfect imagery — powered by AI, crafted by humans. Based in Bangladesh, serving brands worldwide.",
      primaryCta: "Book a Call",
      secondaryCta: "See Our Work",
      imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    },
    about: {
      eyebrow: "Who We Are",
      title: "We Are WEBRING",
      body: "A premium design studio based in Bangladesh, combining AI technology with human creative expertise to deliver world-class product visuals for e-commerce brands globally.",
      philosophy:
        "We take a raw product image and engineer it into a visual that sells — combining AI precision with human artistry.",
    },
    sections: {
      showcase: {
        eyebrow: "Before & After",
        title: "See The Transformation",
        body: "Every image tells a story of transformation. From raw smartphone shots to magazine-ready visuals.",
      },
      services: {
        eyebrow: "What We Do",
        title: "Our Services",
        body: "We combine cutting-edge AI tools with expert human editing to deliver visuals that convert.",
      },
      portfolio: {
        eyebrow: "Our Work",
        title: "Selected Projects",
        body: "A curated collection of our best transformations across industries.",
      },
      pricing: {
        eyebrow: "Investment",
        title: "Simple Pricing",
        body: "Transparent pricing with no hidden fees. Every package includes revisions until you're satisfied.",
      },
      team: {
        eyebrow: "The Team",
        title: "The Minds Behind WEBRING",
        body: "Three creative professionals united by a passion for visual excellence.",
      },
      booking: {
        eyebrow: "Let's Work Together",
        title: "Ready To Make Your Product Irresistible?",
        body: "Book a free 30-minute strategy call. We'll discuss your brand, your goals, and how we can help.",
      },
    },
    contact: {
      email: "hello@webring.studio",
      phone: "+880-XXXXXXXXXX",
      address: "Bangladesh — Available Worldwide",
      socials: {
        instagram: "#",
        facebook: "#",
        linkedin: "#",
        behance: "#",
      },
    },
    booking: {
      timezone: "Asia/Dhaka",
      availability: [
        { dayOfWeek: 0, enabled: true, slots: [{ start: "10:00", end: "17:00" }] },
        { dayOfWeek: 1, enabled: true, slots: [{ start: "10:00", end: "17:00" }] },
        { dayOfWeek: 2, enabled: true, slots: [{ start: "10:00", end: "17:00" }] },
        { dayOfWeek: 3, enabled: true, slots: [{ start: "10:00", end: "17:00" }] },
        { dayOfWeek: 4, enabled: true, slots: [{ start: "10:00", end: "17:00" }] },
        { dayOfWeek: 5, enabled: false, slots: [] },
        { dayOfWeek: 6, enabled: false, slots: [] },
      ],
    },
  },
  services: [
    {
      _id: "svc-1",
      title: "AI Product Photography",
      slug: "ai-product-photography",
      description:
        "Send us your raw product image. We transform it into a professional studio shot with perfect lighting, clean backgrounds, and commercial-grade quality.",
      sampleImageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
      deliverables: [
        "White/gradient studio backgrounds",
        "Shadow & reflection work",
        "Color correction & retouching",
        "Multi-angle variations",
        "Amazon & Shopify optimized",
      ],
      order: 1,
      active: true,
    },
    {
      _id: "svc-2",
      title: "Lifestyle Photography",
      slug: "lifestyle-photography",
      description:
        "Place your product in stunning lifestyle scenes without an expensive photoshoot. AI-generated environments create believable, aspirational imagery.",
      sampleImageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80",
      deliverables: [
        "Home, outdoor, luxury scenes",
        "Model integration (AI)",
        "Platform-specific sizing",
        "Seasonal/thematic variations",
      ],
      order: 2,
      active: true,
    },
    {
      _id: "svc-3",
      title: "E-commerce Visual Package",
      slug: "ecommerce-visual-package",
      description:
        "A complete image set for your e-commerce platform — hero images, detail shots, infographics, and lifestyle images in one cohesive package.",
      sampleImageUrl: "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=600&q=80",
      deliverables: [
        "Main listing image",
        "Feature highlight images",
        "Comparison & infographic images",
        "A+ Content / EBC images",
        "Mobile-optimized crops",
      ],
      order: 3,
      active: true,
    },
    {
      _id: "svc-4",
      title: "Brand Identity",
      slug: "brand-identity",
      description:
        "Complete brand identity design — logo, color system, typography, brand guidelines, and social media presence so your brand is instantly recognizable.",
      sampleImageUrl: "https://images.unsplash.com/photo-1634942537034-2531766767d1?w=600&q=80",
      deliverables: [
        "Logo design",
        "Color & typography system",
        "Brand guideline document",
        "Social media templates",
        "Business card & stationery",
      ],
      order: 4,
      active: true,
    },
  ],
  portfolio: [
    {
      _id: "port-1",
      title: "Premium Watch Campaign",
      category: "AI Photography",
      description: "Transformed a smartphone shot into a premium dark-mood studio visual.",
      beforeImageUrl: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80",
      afterImageUrl: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&q=80",
      featured: true,
      order: 1,
      active: true,
    },
    {
      _id: "port-2",
      title: "Organic Skincare Line",
      category: "Lifestyle",
      description: "Placed organic skincare products into natural, sunlit bathroom environments using AI.",
      beforeImageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&q=80",
      afterImageUrl: "https://images.unsplash.com/photo-1570194065650-d99fb4a38c54?w=800&q=80",
      featured: false,
      order: 2,
      active: true,
    },
    {
      _id: "port-3",
      title: "Fitness Supplement E-com",
      category: "E-commerce",
      description: "Complete visual package including infographics and A+ content for Amazon listing.",
      beforeImageUrl: "https://images.unsplash.com/photo-1593095948071-474c5cc2c4d8?w=800&q=80",
      afterImageUrl: "https://images.unsplash.com/photo-1612363148951-4c0a20a0054e?w=800&q=80",
      featured: false,
      order: 3,
      active: true,
    },
    {
      _id: "port-4",
      title: "Sneaker Levitation",
      category: "AI Photography",
      description: "Dynamic levitation shot with motion blur and stylized lighting.",
      beforeImageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
      afterImageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
      featured: false,
      order: 4,
      active: true,
    },
  ],
  pricing: [
    {
      _id: "price-1",
      name: "Starter",
      description: "Perfect for small brands testing AI photography.",
      price: 199,
      currency: "USD",
      billingNote: "per project",
      features: [
        "5 product images",
        "1 service type",
        "2 revisions",
        "3-day delivery",
      ],
      ctaLabel: "Get Started",
      popular: false,
    },
    {
      _id: "price-2",
      name: "Growth",
      description: "For brands ready to scale their visual content.",
      price: 499,
      currency: "USD",
      billingNote: "per project",
      features: [
        "15 images",
        "3 service types",
        "Unlimited revisions",
        "Lifestyle + studio",
        "5-day delivery",
        "Priority support",
      ],
      ctaLabel: "Book a Call",
      popular: true,
    },
    {
      _id: "price-3",
      name: "Enterprise",
      description: "Custom solution for high-volume brands.",
      price: 999,
      currency: "USD",
      billingNote: "per month",
      features: [
        "Unlimited images",
        "All services included",
        "Dedicated manager",
        "Custom timeline",
        "Monthly retainer",
      ],
      ctaLabel: "Contact Us",
      popular: false,
    },
  ],
  team: [
    {
      _id: "team-1",
      name: "Shiekh Mariful",
      role: "CEO & Creative Director",
      photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
      bio: "Leads the creative vision of WEBRING, ensuring every output meets the highest standard of excellence.",
      socialLinks: [
        { label: "LinkedIn", url: "#" },
        { label: "Instagram", url: "#" },
      ],
    },
    {
      _id: "team-2",
      name: "Many",
      role: "Co-Founder & Growth Lead",
      photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
      bio: "Drives WEBRING's growth strategy, connecting the right brands with transformative visual solutions.",
      socialLinks: [{ label: "LinkedIn", url: "#" }],
    },
    {
      _id: "team-3",
      name: "Sabbir",
      role: "HR Manager & Senior Editor",
      photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
      bio: "Bridges operations with creativity — manages the team while actively shaping each project's visual direction.",
      socialLinks: [
        { label: "Instagram", url: "#" },
        { label: "Behance", url: "#" },
      ],
    },
  ],
};
